[backend]
# something
container="docker" # or (custom)
# something


# match main.toml in directory
["./build/"]
# set settings for build directory 


#match example.toml in config directory
["./example.toml"]
# set settings for example.toml
